import { QURAN_CORPUS, attested } from "./quran-corpus.js";

/**
 * Three-letter Quranic words, chosen and glossed by hand, arranged into cards.
 *
 * WHERE THESE WORDS COME FROM
 *
 * quran-corpus.js is generated by scripts/mine-quran-words.mjs, which sweeps
 * the whole Uthmani text for words of exactly three letters where each letter
 * carries exactly one fatha, kasra or damma — the deck's own alphabet of marks,
 * and nothing more. There are 230 of them. This file picks about seventy of
 * those and says what they mean.
 *
 * The split matters. Nothing here can name a word the corpus does not attest:
 * unattested() lists any that slip through and the tests fail on a non-empty
 * result. So the answer to "are these proper Arabic words" is not my judgement
 * or a dictionary's uptime — it is that every one of them is in the mushaf, at
 * the ayah printed on the card.
 *
 * WHAT IS STILL A HUMAN'S JOB
 *
 * The English glosses below are NOT machine-checked, and cannot be. They are
 * the short classroom sense of the word, not a translation of the ayah it sits
 * in, and a three-letter Arabic verb usually carries several senses this one
 * line does not attempt. Each card shows its ayah reference for exactly this
 * reason: an ustazah who disagrees with a gloss can see the verse it came from
 * and correct the line here.
 *
 * HOW THE CARDS ARE BUILT
 *
 * Following the deck's own design rather than inventing a new one. The printed
 * cards teach by minimal contrast — بَنَتَ beside بُنِتَ, the same letters with
 * the harakat moved — because that is what forces a child to read the marks
 * instead of recognising a shape. Six cards here do the same thing with real
 * words, pairing an active verb with its attested passive: خَلَقَ / خُلِقَ,
 * كَتَبَ / كُتِبَ, وَعَدَ / وُعِدَ. Both halves are in the Quran, so the child gets
 * the deck's exercise and a word worth knowing from the same card.
 *
 * The rest group by sense, so that a card is also a small piece of vocabulary:
 * the words of the heart, the words for coming and going, four things you can
 * point at.
 *
 * WHAT IS LEFT OUT, AND WHY
 *
 * Most of the 230. Three kinds are excluded on purpose:
 *
 *   1. Words that are a particle or pronoun stuck to something else —
 *      وَهُوَ, لَكُمُ, مَعَهُ, فَقَدِ. They are the most frequent hits in the
 *      corpus and the least use: "and he" is not vocabulary, and a child who
 *      learns وَلَهُ as a word has learned a seam, not a word.
 *   2. Verbs carrying a liaison vowel that only exists because of the next
 *      word — يُطِعِ, لَقَدِ, يَجِدِ. The final kasra is a joining artefact, so
 *      the card would be teaching a reading that does not survive on its own.
 *   3. Vocabulary that is real, Quranic, and not for a six-year-old to read
 *      aloud in class: the verbs of killing, cursing, slaughter and marital
 *      relations, and Hellfire by name. No filter can make that call, and the
 *      expletive screen in clean-words.js is not trying to — it catches
 *      accidental obscenity in other languages, not heavy meanings in this
 *      one. This is the judgement call, and it is deliberately a human's.
 *
 * A teacher who wants any of those can add it: the corpus lists every one with
 * its reference, and adding a line here is all it takes.
 */

/* Card titles are for the ustazah, not the child — they say what the card is
   drilling, so a teacher scanning twenty cards can find the one she wants. */
export const QURAN_CARDS = [
  {
    id: "made",
    title: "He made, he did",
    words: ["خَلَقَ", "جَعَلَ", "فَعَلَ", "عَمِلَ"],
  },
  {
    id: "khalaqa-kataba",
    title: "Did it — or was done: خلق، كتب",
    words: ["خَلَقَ", "خُلِقَ", "كَتَبَ", "كُتِبَ"],
  },
  {
    id: "jaala-faala",
    title: "Did it — or was done: جعل، فعل",
    words: ["جَعَلَ", "جُعِلَ", "فَعَلَ", "فُعِلَ"],
  },
  {
    id: "waada-wajada",
    title: "Did it — or was done: وعد، وجد",
    words: ["وَعَدَ", "وُعِدَ", "وَجَدَ", "وُجِدَ"],
  },
  {
    id: "daraba-manaa",
    title: "Did it — or was done: ضرب، منع",
    words: ["ضَرَبَ", "ضُرِبَ", "مَنَعَ", "مُنِعَ"],
  },
  {
    id: "zalama-arada",
    title: "Did it — or was done: ظلم، عرض",
    words: ["ظَلَمَ", "ظُلِمَ", "عَرَضَ", "عُرِضَ"],
  },
  {
    id: "kasra-middle",
    title: "Kasra in the middle",
    words: ["عَلِمَ", "سَمِعَ", "شَهِدَ", "حَفِظَ"],
  },
  {
    id: "heart",
    title: "Words of the heart",
    words: ["رَضِيَ", "رَحِمَ", "غَفَرَ", "شَكَرَ"],
  },
  {
    id: "patience",
    title: "Patience and truth",
    words: ["صَبَرَ", "صَدَقَ", "صَلَحَ", "نَظَرَ"],
  },
  {
    id: "going",
    title: "Coming and going",
    words: ["ذَهَبَ", "دَخَلَ", "رَجَعَ", "قِبَلَ"],
  },
  {
    id: "hands",
    title: "With the hands",
    words: ["كَتَبَ", "فَتَحَ", "حَمَلَ", "بَسَطَ"],
  },
  {
    id: "things",
    title: "Things you can point at",
    words: ["مَطَرُ", "غَنَمُ", "وَرَقِ", "سُبُلَ"],
  },
  {
    id: "mushaf",
    title: "From the mushaf",
    words: ["رُسُلُ", "صُحُفِ", "مَلِكِ", "مَثَلُ"],
  },
  {
    id: "was-done",
    title: "It was done — damma, kasra, fatha",
    words: ["ذُكِرَ", "نُفِخَ", "وُلِدَ", "قُضِيَ"],
  },
  {
    id: "damma-middle",
    title: "Damma in the middle",
    words: ["كَبُرَ", "كَثُرَ", "ضَعُفَ", "بَلَغَ"],
  },
  {
    id: "speaking",
    title: "Speaking and keeping quiet",
    words: ["جَهَرَ", "كَتَمَ", "شَرَحَ", "سَكَتَ"],
  },
  {
    id: "raised",
    title: "Raised up, sent down",
    words: ["بَعَثَ", "رَفَعَ", "نَزَلَ", "فَطَرَ"],
  },
  {
    id: "earning",
    title: "Earning and giving",
    words: ["كَسَبَ", "وَهَبَ", "جَمَعَ", "حَكَمَ"],
  },
  {
    id: "knowing",
    title: "Knowing and forgetting",
    words: ["عَلِمَ", "نَسِيَ", "فَرِحَ", "كَرِهَ"],
  },
  {
    id: "staying",
    title: "Staying a while",
    words: ["حَضَرَ", "سَكَنَ", "بَقِيَ", "لَبِثَ"],
  },
];

/**
 * The classroom sense of each word above — one short line, in the form a
 * six-year-old's ustazah would say it.
 *
 * "he created" rather than "created (3rd person masculine singular perfect)":
 * the gloss is read aloud to a child, so it is a sentence fragment they can
 * hear, and the past tense is kept because that is genuinely what the Arabic
 * form is. Passives are glossed as passives for the same reason — the whole
 * point of the خُلِقَ card is that the harakat changed who did the thing.
 */
export const QURAN_GLOSS = {
  // Making and doing
  خَلَقَ: "he created",
  خُلِقَ: "he was created",
  جَعَلَ: "he made",
  جُعِلَ: "it was made",
  فَعَلَ: "he did",
  فُعِلَ: "it was done",
  عَمِلَ: "he worked, he did",

  // Writing and the hands
  كَتَبَ: "he wrote",
  كُتِبَ: "it was written",
  فَتَحَ: "he opened",
  حَمَلَ: "he carried",
  بَسَطَ: "he spread out",

  // Promising and finding
  وَعَدَ: "he promised",
  وُعِدَ: "he was promised",
  وَجَدَ: "he found",
  وُجِدَ: "it was found",

  // Striking, withholding, wronging
  ضَرَبَ: "he struck",
  ضُرِبَ: "it was struck",
  مَنَعَ: "he held back",
  مُنِعَ: "it was held back",
  ظَلَمَ: "he did wrong",
  ظُلِمَ: "he was wronged",
  عَرَضَ: "he showed it",
  عُرِضَ: "it was shown",

  // Knowing, hearing, guarding
  عَلِمَ: "he knew",
  سَمِعَ: "he heard",
  شَهِدَ: "he saw it himself",
  حَفِظَ: "he guarded it",
  نَسِيَ: "he forgot",
  نَظَرَ: "he looked",

  // The heart
  رَضِيَ: "he was pleased",
  رَحِمَ: "he showed mercy",
  غَفَرَ: "he forgave",
  شَكَرَ: "he gave thanks",
  صَبَرَ: "he was patient",
  صَدَقَ: "he told the truth",
  صَلَحَ: "he was good",
  فَرِحَ: "he was glad",
  كَرِهَ: "he disliked it",

  // Coming and going
  ذَهَبَ: "he went",
  دَخَلَ: "he went in",
  رَجَعَ: "he came back",
  قِبَلَ: "toward, the side of",

  // Things
  مَطَرُ: "rain",
  غَنَمُ: "sheep",
  وَرَقِ: "leaves",
  سُبُلَ: "paths",
  رُسُلُ: "messengers",
  صُحُفِ: "scriptures",
  مَلِكِ: "King",
  مَثَلُ: "a likeness",

  // Done to it
  ذُكِرَ: "he was mentioned",
  نُفِخَ: "it was blown",
  وُلِدَ: "he was born",
  قُضِيَ: "it was settled",

  // Big, many, weak
  كَبُرَ: "it was great",
  كَثُرَ: "it became many",
  ضَعُفَ: "it was weak",
  بَلَغَ: "he reached it",

  // Speaking
  جَهَرَ: "he said it out loud",
  كَتَمَ: "he kept it hidden",
  شَرَحَ: "he opened it wide",
  سَكَتَ: "it went quiet",

  // Raising and sending
  بَعَثَ: "he raised him up",
  رَفَعَ: "he lifted it",
  نَزَلَ: "it came down",
  فَطَرَ: "he originated it",

  // Earning and giving
  كَسَبَ: "he earned",
  وَهَبَ: "he gave a gift",
  جَمَعَ: "he gathered",
  حَكَمَ: "he judged",

  // Staying
  حَضَرَ: "he was there",
  سَكَنَ: "he lived there",
  بَقِيَ: "it stayed",
  لَبِثَ: "he stayed a while",
};

/** Every word used on a card above, deduplicated. */
export function curatedWords() {
  return [...new Set(QURAN_CARDS.flatMap((c) => c.words))];
}

/**
 * Curated words the corpus does not attest — which must always be empty.
 *
 * This is the guard that makes the whole feature trustworthy. A typo in a
 * harakah above produces a string that is not in the mushaf, and without this
 * check it would render perfectly and teach a child a word that does not
 * exist. The tests fail on any non-empty result, so the only words that can
 * reach a card are words the mining run found in the text.
 */
export function unattested() {
  return curatedWords().filter((w) => !attested(w));
}

/** Curated words with no English gloss — also expected to be empty. */
export function unglossed() {
  return curatedWords().filter((w) => !QURAN_GLOSS[w]);
}

/** The ayah a word was taken from, e.g. "2:29", or null if it is not mined. */
export function ayahOf(word) {
  return attested(word)?.ref ?? null;
}

/** How many times the Quran uses this word, for a teacher ordering a lesson. */
export function countOf(word) {
  return attested(word)?.count ?? 0;
}

/** The whole mined corpus, for a teacher looking for a word to add. */
export { QURAN_CORPUS };
