export const JUZ_AMMA_SURAHS = [
  { number: 78, name: "An-Naba", ayahCount: 40 },
  { number: 79, name: "An-Nazi'at", ayahCount: 46 },
  { number: 80, name: "Abasa", ayahCount: 42 },
  { number: 81, name: "At-Takwir", ayahCount: 29 },
  { number: 82, name: "Al-Infitar", ayahCount: 19 },
  { number: 83, name: "Al-Mutaffifin", ayahCount: 36 },
  { number: 84, name: "Al-Inshiqaq", ayahCount: 25 },
  { number: 85, name: "Al-Buruj", ayahCount: 22 },
  { number: 86, name: "At-Tariq", ayahCount: 17 },
  { number: 87, name: "Al-Ala", ayahCount: 19 },
  { number: 88, name: "Al-Ghashiyah", ayahCount: 26 },
  { number: 89, name: "Al-Fajr", ayahCount: 30 },
  { number: 90, name: "Al-Balad", ayahCount: 20 },
  { number: 91, name: "Ash-Shams", ayahCount: 15 },
  { number: 92, name: "Al-Layl", ayahCount: 21 },
  { number: 93, name: "Ad-Duha", ayahCount: 11 },
  { number: 94, name: "Ash-Sharh", ayahCount: 8 },
  { number: 95, name: "At-Tin", ayahCount: 8 },
  { number: 96, name: "Al-Alaq", ayahCount: 19 },
  { number: 97, name: "Al-Qadr", ayahCount: 5 },
  { number: 98, name: "Al-Bayyinah", ayahCount: 8 },
  { number: 99, name: "Az-Zalzalah", ayahCount: 8 },
  { number: 100, name: "Al-Adiyat", ayahCount: 11 },
  { number: 101, name: "Al-Qariah", ayahCount: 11 },
  { number: 102, name: "At-Takathur", ayahCount: 8 },
  { number: 103, name: "Al-Asr", ayahCount: 3 },
  { number: 104, name: "Al-Humazah", ayahCount: 9 },
  { number: 105, name: "Al-Fil", ayahCount: 5 },
  { number: 106, name: "Quraysh", ayahCount: 4 },
  { number: 107, name: "Al-Maun", ayahCount: 7 },
  { number: 108, name: "Al-Kawthar", ayahCount: 3 },
  { number: 109, name: "Al-Kafirun", ayahCount: 6 },
  { number: 110, name: "An-Nasr", ayahCount: 3 },
  { number: 111, name: "Al-Masad", ayahCount: 5 },
  { number: 112, name: "Al-Ikhlas", ayahCount: 4 },
  { number: 113, name: "Al-Falaq", ayahCount: 5 },
  { number: 114, name: "An-Nas", ayahCount: 6 },
];

export function surahName(number) {
  return JUZ_AMMA_SURAHS.find((s) => s.number === Number(number))?.name ?? `Surah ${number}`;
}
