// AUTO-GENERATED by the dzikir extraction pipelines (NU + Ba'alawi). Do not hand-edit.
// Small static index (no Arabic text) used by the /dzikir landing page.
export const CATALOG = [
  {
    "key": "wirid",
    "label": "Wirid & Zikir",
    "blurb": "Daily litanies, Asma'ul Husna, Ratib, Hizib, Dala'il al-Khayrat, Manaqib & Istighotsah.",
    "sections": [
      {
        "key": "wirid/dalailul-khairat",
        "group": "wirid",
        "slug": "dalailul-khairat",
        "title": "Dala'il al-Khayrat",
        "count": 708,
        "subCount": 13
      },
      {
        "key": "wirid/istighotsah-mujahadah",
        "group": "wirid",
        "slug": "istighotsah-mujahadah",
        "title": "Istighathah & Mujahadah",
        "count": 283,
        "subCount": 7
      },
      {
        "key": "wirid/ratib",
        "group": "wirid",
        "slug": "ratib",
        "title": "Ratib Litanies",
        "count": 281,
        "subCount": 6
      },
      {
        "key": "wirid/hizib",
        "group": "wirid",
        "slug": "hizib",
        "title": "Hizb Litanies",
        "count": 266,
        "subCount": 9
      },
      {
        "key": "wirid/shalawat",
        "group": "wirid",
        "slug": "shalawat",
        "title": "Salawat",
        "count": 207,
        "subCount": 35
      },
      {
        "key": "wirid/munajat",
        "group": "wirid",
        "slug": "munajat",
        "title": "The 99 Names of Allah",
        "count": 175,
        "subCount": 3
      },
      {
        "key": "wirid/wirid-harian",
        "group": "wirid",
        "slug": "wirid-harian",
        "title": "Daily Litany",
        "count": 151,
        "subCount": 6
      },
      {
        "key": "wirid/manaqib-syekh-abdul-qadir",
        "group": "wirid",
        "slug": "manaqib-syekh-abdul-qadir",
        "title": "Manaqib of Shaykh Abd al-Qadir",
        "count": 93,
        "subCount": 9
      },
      {
        "key": "wirid/awrad-pagi-petang",
        "group": "wirid",
        "slug": "awrad-pagi-petang",
        "title": "Morning & Evening Awrad (Ba 'Alawi)",
        "count": 9,
        "subCount": 1
      },
      {
        "key": "wirid/awrad-jumat",
        "group": "wirid",
        "slug": "awrad-jumat",
        "title": "Friday Awrad (Ba 'Alawi)",
        "count": 52,
        "subCount": 5
      },
      {
        "key": "wirid/ratib-hizib-baalawi",
        "group": "wirid",
        "slug": "ratib-hizib-baalawi",
        "title": "Ahzab & Ratib (Ba 'Alawi)",
        "count": 115,
        "subCount": 8
      },
      {
        "key": "wirid/tahsinat",
        "group": "wirid",
        "slug": "tahsinat",
        "title": "Tahsinat & Huruz (Protections)",
        "count": 96,
        "subCount": 8
      },
      {
        "key": "wirid/wird-ibn-tahir",
        "group": "wirid",
        "slug": "wird-ibn-tahir",
        "title": "Wird of Habib Abdullah bin Husayn bin Tahir",
        "count": 7,
        "subCount": 1
      },
      {
        "key": "wirid/ayat-pilihan",
        "group": "wirid",
        "slug": "ayat-pilihan",
        "title": "Selected Qur'anic Verses",
        "count": 45,
        "subCount": 4
      },
      {
        "key": "wirid/nafhah-anbariyyah",
        "group": "wirid",
        "slug": "nafhah-anbariyyah",
        "title": "An-Nafhah al-'Anbariyyah (Salawat)",
        "count": 40,
        "subCount": 1
      },
      {
        "key": "wirid/badr-suud",
        "group": "wirid",
        "slug": "badr-suud",
        "title": "Badr as-Su'ud (Salawat)",
        "count": 23,
        "subCount": 1
      },
      {
        "key": "wirid/sharh-sadr",
        "group": "wirid",
        "slug": "sharh-sadr",
        "title": "Sharh as-Sadr (Salawat)",
        "count": 75,
        "subCount": 1
      },
      {
        "key": "wirid/rawd-anwar",
        "group": "wirid",
        "slug": "rawd-anwar",
        "title": "Rawd al-Anwar wa Kanz al-Asrar",
        "count": 13,
        "subCount": 1
      },
      {
        "key": "wirid/jalan-baalawi",
        "group": "wirid",
        "slug": "jalan-baalawi",
        "title": "The Ba 'Alawi Path",
        "count": 28,
        "subCount": 1
      },
      {
        "key": "wirid/kawakib-mudiyyah",
        "group": "wirid",
        "slug": "kawakib-mudiyyah",
        "title": "Al-Kawakib al-Mudiyyah (Salawat)",
        "count": 109,
        "subCount": 1
      },
      {
        "key": "wirid/majma-lataif",
        "group": "wirid",
        "slug": "majma-lataif",
        "title": "Majma' al-Lata'if (7 Daily Hizbs)",
        "count": 321,
        "subCount": 8
      },
      {
        "key": "wirid/shalawat-ahmad-attas",
        "group": "wirid",
        "slug": "shalawat-ahmad-attas",
        "title": "Salawat of Habib Ahmad al-Attas",
        "count": 103,
        "subCount": 1
      },
      {
        "key": "wirid/sharaf-asna",
        "group": "wirid",
        "slug": "sharaf-asna",
        "title": "Ash-Sharaf al-Asna",
        "count": 89,
        "subCount": 1
      }
    ]
  },
  {
    "key": "doa",
    "label": "Doa",
    "blurb": "Everyday supplications — morning to night, and for every occasion.",
    "sections": [
      {
        "key": "doa/doa-para-nabi-di-al-quran",
        "group": "doa",
        "slug": "doa-para-nabi-di-al-quran",
        "title": "Prophets' Supplications in the Qur'an",
        "count": 104,
        "subCount": 14
      },
      {
        "key": "doa/doa-shalat",
        "group": "doa",
        "slug": "doa-shalat",
        "title": "The Ritual Prayer (Salah)",
        "count": 53,
        "subCount": 20
      },
      {
        "key": "doa/doa-waktu-tertentu",
        "group": "doa",
        "slug": "doa-waktu-tertentu",
        "title": "Particular Times",
        "count": 31,
        "subCount": 12
      },
      {
        "key": "doa/doa-haji-umrah",
        "group": "doa",
        "slug": "doa-haji-umrah",
        "title": "Hajj & Umrah",
        "count": 29,
        "subCount": 21
      },
      {
        "key": "doa/doa-pernikahan-rumah-tangga",
        "group": "doa",
        "slug": "doa-pernikahan-rumah-tangga",
        "title": "Marriage & Family",
        "count": 27,
        "subCount": 10
      },
      {
        "key": "doa/doa-baca-al-quran",
        "group": "doa",
        "slug": "doa-baca-al-quran",
        "title": "Reciting the Qur'an",
        "count": 26,
        "subCount": 7
      },
      {
        "key": "doa/doa-kematian",
        "group": "doa",
        "slug": "doa-kematian",
        "title": "Death & Bereavement",
        "count": 26,
        "subCount": 6
      },
      {
        "key": "doa/doa-wudhu",
        "group": "doa",
        "slug": "doa-wudhu",
        "title": "Ablution (Wudu)",
        "count": 23,
        "subCount": 11
      },
      {
        "key": "doa/doa-hamil-dan-persalinan",
        "group": "doa",
        "slug": "doa-hamil-dan-persalinan",
        "title": "Pregnancy & Childbirth",
        "count": 21,
        "subCount": 7
      },
      {
        "key": "doa/doa-keseharian",
        "group": "doa",
        "slug": "doa-keseharian",
        "title": "Everyday Supplications",
        "count": 19,
        "subCount": 19
      },
      {
        "key": "doa/doa-tolak-bala",
        "group": "doa",
        "slug": "doa-tolak-bala",
        "title": "Protection from Harm",
        "count": 13,
        "subCount": 13
      },
      {
        "key": "doa/doa-ilmu",
        "group": "doa",
        "slug": "doa-ilmu",
        "title": "Seeking Knowledge",
        "count": 12,
        "subCount": 9
      },
      {
        "key": "doa/doa-kualitas-diri",
        "group": "doa",
        "slug": "doa-kualitas-diri",
        "title": "Self & Character",
        "count": 10,
        "subCount": 10
      },
      {
        "key": "doa/doa-rezeki",
        "group": "doa",
        "slug": "doa-rezeki",
        "title": "Provision & Sustenance",
        "count": 10,
        "subCount": 9
      },
      {
        "key": "doa/doa-perjalanan",
        "group": "doa",
        "slug": "doa-perjalanan",
        "title": "Travel",
        "count": 9,
        "subCount": 7
      },
      {
        "key": "doa/doa-kesehatan",
        "group": "doa",
        "slug": "doa-kesehatan",
        "title": "Health & Healing",
        "count": 5,
        "subCount": 5
      },
      {
        "key": "other/uncat",
        "group": "doa",
        "slug": "uncat",
        "title": "Other Supplications",
        "count": 2,
        "subCount": 0
      },
      {
        "key": "doa/empat-puluh-doa",
        "group": "doa",
        "slug": "empat-puluh-doa",
        "title": "The Forty Supplications",
        "count": 63,
        "subCount": 11
      },
      {
        "key": "doa/doa-penyembuhan-ruqyah",
        "group": "doa",
        "slug": "doa-penyembuhan-ruqyah",
        "title": "Healing & Ruqyah (Ba 'Alawi)",
        "count": 76,
        "subCount": 8
      },
      {
        "key": "doa/doa-kesulitan-hajat",
        "group": "doa",
        "slug": "doa-kesulitan-hajat",
        "title": "Difficulties, Needs & Provision",
        "count": 72,
        "subCount": 13
      },
      {
        "key": "doa/doa-setelah-shalat-nabawi",
        "group": "doa",
        "slug": "doa-setelah-shalat-nabawi",
        "title": "Prophetic Supplications After Each Prayer",
        "count": 45,
        "subCount": 10
      },
      {
        "key": "doa/doa-majelis-ilmu",
        "group": "doa",
        "slug": "doa-majelis-ilmu",
        "title": "Knowledge & Gatherings (Ba 'Alawi)",
        "count": 33,
        "subCount": 5
      },
      {
        "key": "doa/doa-keluarga-baalawi",
        "group": "doa",
        "slug": "doa-keluarga-baalawi",
        "title": "Marriage & Family (Ba 'Alawi)",
        "count": 46,
        "subCount": 4
      },
      {
        "key": "doa/jenazah-baalawi",
        "group": "doa",
        "slug": "jenazah-baalawi",
        "title": "The Funeral Prayer (How-to)",
        "count": 16,
        "subCount": 1
      }
    ]
  },
  {
    "key": "maulid",
    "label": "Maulid",
    "blurb": "Diba', Barzanji, Simthud Durar, Burdah, Syaraful Anam and more.",
    "sections": [
      {
        "key": "maulid/syaraful-anam",
        "group": "maulid",
        "slug": "syaraful-anam",
        "title": "Mawlid Sharaf al-Anam",
        "count": 320,
        "subCount": 39
      },
      {
        "key": "maulid/qasidah-burdah",
        "group": "maulid",
        "slug": "qasidah-burdah",
        "title": "Qasidat al-Burdah (Poem of the Cloak)",
        "count": 179,
        "subCount": 10
      },
      {
        "key": "maulid/adl-dliyaul-lami",
        "group": "maulid",
        "slug": "adl-dliyaul-lami",
        "title": "Adh-Dhiya' al-Lami'",
        "count": 174,
        "subCount": 11
      },
      {
        "key": "maulid/maulid-al-azab",
        "group": "maulid",
        "slug": "maulid-al-azab",
        "title": "Mawlid al-'Azab",
        "count": 151,
        "subCount": 11
      },
      {
        "key": "maulid/maulid-dibai",
        "group": "maulid",
        "slug": "maulid-dibai",
        "title": "Mawlid ad-Diba'i",
        "count": 151,
        "subCount": 29
      },
      {
        "key": "maulid/maulid-simthud-duror",
        "group": "maulid",
        "slug": "maulid-simthud-duror",
        "title": "Simt al-Durar (String of Pearls)",
        "count": 107,
        "subCount": 17
      },
      {
        "key": "maulid/maulidul-barzanji",
        "group": "maulid",
        "slug": "maulidul-barzanji",
        "title": "Mawlid al-Barzanji",
        "count": 93,
        "subCount": 20
      },
      {
        "key": "maulid/hadrah-baalawi",
        "group": "maulid",
        "slug": "hadrah-baalawi",
        "title": "Hadrahs of the Ba 'Alawi",
        "count": 12,
        "subCount": 1
      },
      {
        "key": "maulid/qasidah-klasik",
        "group": "maulid",
        "slug": "qasidah-klasik",
        "title": "Classical Qasidahs",
        "count": 13,
        "subCount": 1
      },
      {
        "key": "maulid/qasidah-fatimiyyah",
        "group": "maulid",
        "slug": "qasidah-fatimiyyah",
        "title": "For Sayyidah Fatimah az-Zahra",
        "count": 13,
        "subCount": 2
      },
      {
        "key": "maulid/maulid-syarab-tahur",
        "group": "maulid",
        "slug": "maulid-syarab-tahur",
        "title": "Mawlid ash-Sharab at-Tahur",
        "count": 47,
        "subCount": 7
      }
    ]
  },
  {
    "key": "haji-dan-umrah",
    "label": "Haji & Umrah",
    "blurb": "The rites, intentions and supplications of the pilgrimage.",
    "sections": [
      {
        "key": "haji-dan-umrah/doa-saat-di-arafah",
        "group": "haji-dan-umrah",
        "slug": "doa-saat-di-arafah",
        "title": "At Arafah",
        "count": 123,
        "subCount": 10
      },
      {
        "key": "haji-dan-umrah/doa-tawaf",
        "group": "haji-dan-umrah",
        "slug": "doa-tawaf",
        "title": "Tawaf",
        "count": 52,
        "subCount": 12
      },
      {
        "key": "haji-dan-umrah/niat-ihram",
        "group": "haji-dan-umrah",
        "slug": "niat-ihram",
        "title": "Ihram Intentions",
        "count": 27,
        "subCount": 6
      },
      {
        "key": "haji-dan-umrah/doa-saat-di-madinah",
        "group": "haji-dan-umrah",
        "slug": "doa-saat-di-madinah",
        "title": "In Madinah",
        "count": 17,
        "subCount": 10
      },
      {
        "key": "haji-dan-umrah/doa-setelah-shalat-sunnah",
        "group": "haji-dan-umrah",
        "slug": "doa-setelah-shalat-sunnah",
        "title": "Arriving Home",
        "count": 16,
        "subCount": 4
      },
      {
        "key": "haji-dan-umrah/doa-sai",
        "group": "haji-dan-umrah",
        "slug": "doa-sai",
        "title": "Sa'i",
        "count": 14,
        "subCount": 11
      },
      {
        "key": "haji-dan-umrah/doa-saat-di-mina",
        "group": "haji-dan-umrah",
        "slug": "doa-saat-di-mina",
        "title": "At Mina",
        "count": 11,
        "subCount": 6
      },
      {
        "key": "haji-dan-umrah/doa-saat-di-muzdalifah",
        "group": "haji-dan-umrah",
        "slug": "doa-saat-di-muzdalifah",
        "title": "At Muzdalifah",
        "count": 10,
        "subCount": 3
      },
      {
        "key": "haji-dan-umrah/doa-saat-di-makkah",
        "group": "haji-dan-umrah",
        "slug": "doa-saat-di-makkah",
        "title": "In Makkah",
        "count": 8,
        "subCount": 6
      },
      {
        "key": "haji-dan-umrah/doa-dalam-perjalanan",
        "group": "haji-dan-umrah",
        "slug": "doa-dalam-perjalanan",
        "title": "On the Journey",
        "count": 6,
        "subCount": 6
      },
      {
        "key": "haji-dan-umrah/bacaan-talbiyah-dan-shalawat",
        "group": "haji-dan-umrah",
        "slug": "bacaan-talbiyah-dan-shalawat",
        "title": "Talbiyah & Salawat",
        "count": 3,
        "subCount": 3
      },
      {
        "key": "haji-dan-umrah/doa-bercukur-tahallul",
        "group": "haji-dan-umrah",
        "slug": "doa-bercukur-tahallul",
        "title": "Shaving (Tahallul)",
        "count": 2,
        "subCount": 2
      },
      {
        "key": "haji-dan-umrah/doa-tawaf-wada",
        "group": "haji-dan-umrah",
        "slug": "doa-tawaf-wada",
        "title": "Farewell Tawaf (Wada')",
        "count": 2,
        "subCount": 2
      }
    ]
  },
  {
    "key": "ziyarah",
    "label": "Ziyarah",
    "blurb": "Visits to the Prophet صلى الله عليه وسلم, the Ahl al-Bayt, companions and the righteous — Makkah, Madinah, Tarim and beyond.",
    "sections": [
      {
        "key": "ziyarah/makkah",
        "group": "ziyarah",
        "slug": "makkah",
        "title": "Makkah al-Mukarramah",
        "count": 84,
        "subCount": 5
      },
      {
        "key": "ziyarah/muwajahah",
        "group": "ziyarah",
        "slug": "muwajahah",
        "title": "Facing the Prophet ﷺ",
        "count": 11,
        "subCount": 1
      },
      {
        "key": "ziyarah/baqi-madinah",
        "group": "ziyarah",
        "slug": "baqi-madinah",
        "title": "Baqi' & Madinah",
        "count": 110,
        "subCount": 6
      },
      {
        "key": "ziyarah/tarim-lainnya",
        "group": "ziyarah",
        "slug": "tarim-lainnya",
        "title": "Tarim & Beyond",
        "count": 22,
        "subCount": 1
      }
    ]
  },
  {
    "key": "spesial",
    "label": "Seasonal",
    "blurb": "Ramadan, Isra' & Mi'raj, Eid and the blessed seasons of the year.",
    "sections": [
      {
        "key": "spesial/ramadhan",
        "group": "spesial",
        "slug": "ramadhan",
        "title": "Ramadan",
        "count": 97,
        "subCount": 17
      },
      {
        "key": "spesial/malam-ramadhan",
        "group": "spesial",
        "slug": "malam-ramadhan",
        "title": "Ramadan Evening Poems",
        "count": 22,
        "subCount": 1
      },
      {
        "key": "spesial/khatam-quran",
        "group": "spesial",
        "slug": "khatam-quran",
        "title": "Completion of the Qur'an",
        "count": 17,
        "subCount": 1
      }
    ]
  }
];

export const SECTION_INDEX = Object.fromEntries(
  CATALOG.flatMap((g) => g.sections.map((s) => [s.key, { ...s, groupLabel: g.label }]))
);
