import { CATALOG } from "./catalog";

/**
 * Reading order across the whole library, flattened.
 *
 * Kept out of catalog.js on purpose — that file is regenerated by the
 * extraction pipeline and says not to hand-edit it. The order here is simply
 * the catalog's own order: groups as listed, sections within each group.
 */
const ORDER = CATALOG.flatMap((g) =>
  g.sections.map((s) => ({
    key: s.key,
    group: s.group,
    slug: s.slug,
    title: s.title,
    groupLabel: g.label,
  }))
);

export const SECTION_COUNT = ORDER.length;

/**
 * The collections either side of `key`, for prev/next paging.
 *
 * Deliberately does NOT wrap: at the first or last collection the respective
 * side is null and the control renders disabled. Silently looping back to the
 * start reads as a bug when you are 40 collections deep.
 *
 * Paging runs across group boundaries so a teacher can move through everything
 * without returning to the index; `groupLabel` is exposed so the control can
 * show when the next tap crosses into a different group.
 */
/**
 * Every collection in the same group as `key`, in catalog order.
 *
 * Drives the tab strip at the top of a collection: a teacher reading Ratib
 * sees the other Wirid & Zikir collections either side and can move between
 * them without going back to the index. Group-scoped on purpose — the strip
 * answers "what else is in this section", while prev/next paging below still
 * runs across the whole library.
 */
export function siblingsOf(key) {
  const group = CATALOG.find((g) => g.sections.some((s) => s.key === key));
  if (!group) return [];
  return group.sections.map((s) => ({
    key: s.key,
    group: s.group,
    slug: s.slug,
    title: s.title,
    count: s.count,
  }));
}

export function neighboursOf(key) {
  const i = ORDER.findIndex((s) => s.key === key);
  if (i < 0) return { prev: null, next: null, position: 0, total: ORDER.length };
  return {
    prev: i > 0 ? ORDER[i - 1] : null,
    next: i < ORDER.length - 1 ? ORDER[i + 1] : null,
    position: i + 1,
    total: ORDER.length,
  };
}
